### ISSUE TITLE
資料夾批次處理

### ISSUE THREAD

**Issue by L1247** [ADT109119/WhisperGUI#2]
希望能夠直接使用資料夾，將數個影片放入該資料夾後
自動迴圈跑完該資料夾內所有影片的字幕

`使用情境為：點擊一次輸出全部影片的字幕，人就去睡覺了 `

**Comment by ADT109119** [comment]
因為考慮到怕資料夾內有不該出現的檔案
以及如果這樣做
每次都要先將檔案移到資料夾

所以這邊我把它做成可以直接選擇多個檔案
將檔案加到列表再做處理的形式
![pic](https://user-images.githubusercontent.com/106337749/221340883-4b437d03-97fc-42ee-821e-dd04096323fe.png)

**Comment by L1247** [comment]
可以使用 感謝你的更新
