### ISSUE TITLE
large v3 兼容性

### ISSUE THREAD

**Issue by VeeDou** [ADT109119/WhisperGUI#8]
large v3 更新了，但是它只有 safetensors 格式，似乎不兼容了
 [model.safetensors](https://huggingface.co/openai/whisper-large-v3/blob/main/model.safetensors)

**Comment by ADT109119** [comment]
已新增 `update.bat` 批次檔，用來升級 `openai-whisper` 版本，程式也已直接新增 `large-v3` 的選項可以使用
